SET search_path TO ai;

CREATE TABLE IF NOT EXISTS auditoria_uso_ia (
    auditoria_ia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_oidc VARCHAR(255) NOT NULL,
    tipo_uso_ia VARCHAR(100) NOT NULL,
    ejemplar_id BIGINT NULL,
    prompt TEXT NOT NULL,
    resultado_resumen TEXT NOT NULL,
    consultado_en TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auditoria_uso_ia_subject_oidc
    ON auditoria_uso_ia(subject_oidc);

CREATE INDEX IF NOT EXISTS idx_auditoria_uso_ia_consultado_en
    ON auditoria_uso_ia(consultado_en);
